language: ruby
rvm:
- '2.3.1'
sudo: false
cache:
  bundler: true
  directories:
    - vendor/assets/bower_components
before_cache:
- cat bower.json > vendor/assets/bower_components/bower.json
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
  - PARALLEL_TEST_PROCESSORS=2
  matrix:
  - TEST_SUITE=vmdb PARALLEL=true SPEC_OPTS='--seed=46777 --bisect=verbose'
matrix:
  fast_finish: true
addons:
  postgresql: '9.4'
before_install:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
before_script:
- bundle exec rake test:$TEST_SUITE:setup
script:
- bundle exec rspec ./spec/models/job_proxy_dispatcher_spec.rb[1:1:1:5:1,1:1:1:6:1,1:1:1:7:1,1:1:1:8:1,1:1:1:9:1,1:1:1:9:2,1:1:1:9:3,1:1:2:1:1,1:1:2:1:2,1:1:2:2:1,1:1:2:3:1,1:1:2:4:1,1:1:2:4:2,1:1:2:4:3,1:1:2:4:4,1:1:3:1,1:1:3:2]
after_failure:
- source ${TRAVIS_BUILD_DIR}/tools/ci/after_failure.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7af45001fe6b7a4039f2
    on_success: change
    on_failure: always
    on_start: never
